Squelch some GCC warnings with ooh323c. [skip ci]
./sessions.c: In function ‘sessions_init’:
./sessions.c:339:3: warning: implicit declaration of function
‘ooH323EpInitialize’; did you mean ‘ooH323HangCall’?
[-Wimplicit-function-declaration]

./sessions.c:340:3: warning: implicit declaration of function
‘ooH323EpDisableAutoAnswer’ [-Wimplicit-function-declaration]

./sessions.c:998:86: warning: unused parameter ‘len’
[-Wunused-parameter]

Skip CI because the CI systems build tcpslice w/o the library.