Remove the broken vfprintf() replacement.
In Cirrus CI FreeBSD ./configure for some reason could find neither
vfprintf() nor strlcpy() (in my FreeBSD it finds both, and in my Linux
it finds vfprintf() only). That's why my working copies compiled fine,
but all Cirrus CI copies (FreeBSD 11, 12 and 13) had errored:

./vfprintf.c:33:10: fatal error: 'interface.h' file not found

For clarity, interface.h never existed in tcpslice -- the #include came
with vfprintf.c from tcpdump, which suggests the file never compiled
before. Removing the #include line from vfprintf.c made it clear the
declaration was conflicting with FreeBSD vfprintf(), which actually
exists, and the implementation would not compile anyway:

./vfprintf.c:37:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
./vfprintf.c:38:8: error: promoted type 'FILE *' (aka 'struct __sFILE *') of K&R function parameter is not compatible with the parameter type 'FILE *restrict' (aka 'struct __sFILE *restrict') declared in a previous prototype [-Werror,-Wknr-promoted-parameter]
./vfprintf.c:39:8: error: promoted type 'char *' of K&R function parameter is not compatible with the parameter type 'const char *restrict' declared in a previous prototype [-Werror,-Wknr-promoted-parameter]
./vfprintf.c:44:10: error: no member named '_flag' in 'struct __sFILE'; did you mean '_flags'?
./vfprintf.c:44:18: error: use of undeclared identifier '_IOWRT'
./vfprintf.c:45:10: error: no member named '_flag' in 'struct __sFILE'; did you mean '_flags'?
./vfprintf.c:45:18: error: use of undeclared identifier '_IORW'
./vfprintf.c:46:7: error: no member named '_flag' in 'struct __sFILE'; did you mean '_flags'?
./vfprintf.c:46:16: error: use of undeclared identifier '_IOWRT'
./vfprintf.c:50:8: error: implicit declaration of function '_doprnt' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
./vfprintf.c:50:8: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]

Tcpdump since commit cc47971 no longer tries to provide its own
vfprintf(), do the same thing here and remove vfprintf.c and its props.
This fixes Cirrus CI FreeBSD build.