Fix compile errors with libosip2 4.1.0.
Found using gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0; it looks like the
library API has changed since 2006.

./sessions.c: In function 'sip_get_address':

./sessions.c:780:30: error: incompatible type for argument 1 of
'osip_list_eol'

/usr/include/osipparser2/osip_list.h:129:7: note: expected 'const
osip_list_t * {aka const struct osip_list *}' but argument is of type
'osip_list_t {aka struct osip_list}'

./sessions.c:783:41: error: incompatible type for argument 1 of
'osip_list_get'

/usr/include/osipparser2/osip_list.h:142:9: note: expected 'const
osip_list_t * {aka const struct osip_list *}' but argument is of type
'osip_list_t {aka struct osip_list}'